### ISSUE TITLE
Init Sails.js project

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#1]
- create a new project
- add apidoc for documentation
- set up MySQL via https://aws.amazon.com/ru/rds/mysql/ in the cloud(use your AWS account and free tier)
- use API versioning(*/api/v1/...*)

**Comment by oskvortsov-bmt** [comment]
1-3 hors

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/17/17 - 10/17/17
Work session total: 0:03:54

Grand total: 0:03:54

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/18/17 - 10/18/17
Work session total: 0:21:09

Grand total: 0:25:03

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/19/17 - 10/19/17
Work session total: 2:34:42

Grand total: 2:59:45
