### ISSUE TITLE
New functional for the Customer and Job Scoring Editor pages

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#19]
https://github.com/BestMood-Tech/Hirefy-client/issues/19

Check out this UI task and estimate how much work for the API is it.

**Comment by oskvortsov-bmt** [comment]
5-8 hours

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/01/17 - 11/01/17
Work session total: 3:40:26

Grand total: 3:40:26

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/02/17 - 11/02/17
Work session total: 0:33:28

Grand total: 4:13:54
