### ISSUE TITLE
Registration and login

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#2]
- add Passport.js auth with JWT
- add Users model to the DB
- add documentation for this API

**Comment by oskvortsov-bmt** [comment]
1-2 hours

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/19/17 - 10/19/17
Work session total: 0:47:45

Grand total: 0:47:45

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/19/17 - 10/20/17
Work session total: 3:54:26

Grand total: 4:42:11
