### ISSUE TITLE
load speed and performance

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#22]
> I tested out a job we ran recently for Music Victoria, MUS002... they had 251 applicants and I wanted to see how it handles all of the info. 
I broke the 251 applicants into 4 x csv's for upload to replicate what it will be like when we a fresh upload every day. 
The first 3 x uploads went ok. They got progressively slower the more data that got added. On the 4th chunk of data (the last 30 applicants) I had to try the upload a couple of times before it worked. It just seemed to time out.
Here are the csv's and the JSON I used if you'd like to create a new job and give it a test yourself.

[JSON](https://url.upwork.com/_01oEWBWDVY78NQru7fWMHwVr5sLGUHVIdg)
[CSV1](https://url.upwork.com/_01oEWBWDVY78M7XImQS8tUbtNwQhoSu99v)
[CSV2](https://url.upwork.com/_01oEWBWDVY78P7COjwG_d2YazWuktcHnTy)
[CSV3](https://url.upwork.com/_01oEWBWDVY78NO0plltxXWTzM4XIm2lsWe)
[CSV4](https://url.upwork.com/_01oEWBWDVY78MCHBcU4BVqGTifj-OifYVF)

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/17/17 - 11/17/17
Work session total: 1:31:46

Grand total: 1:31:46

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/18/17 - 11/18/17
Work session total: 3:23:49

Grand total: 4:55:35

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/19/17 - 11/19/17
Work session total: 1:25:13

Grand total: 6:20:48
