### ISSUE TITLE
Candidate Profile Page

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#24]
See https://github.com/BestMood-Tech/Hirefy-client/issues/31

**Comment by oskvortsov-bmt** [comment]
2-4 hours

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/21/17 - 11/21/17
Work session total: 1:12:18

Grand total: 1:12:18

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/22/17 - 11/22/17
Work session total: 4:10:39

Grand total: 5:22:57

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/23/17 - 11/23/17
Work session total: 0:36:42

Grand total: 5:59:39
