### ISSUE TITLE
surveyID

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#25]
The app is currently using the surveyID we manually add to the JSON file. This causes an issue if we create a new job and upload a JSON file, but forget to change the surveyID... it wipes the previous job using that JSON file.

Can we change the app to allocate its own surveyID when a JSON is uploaded? No need for us to add this manually in the JSON.

**Comment by oskvortsov-bmt** [comment]
2-4 hours

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/23/17 - 11/24/17
Work session total: 0:27:14

Grand total: 0:27:14

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/24/17 - 11/24/17
Work session total: 0:18:14

Grand total: 0:45:28
