### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#27]
under Music Victoria, if you take a look at the first job "MUS003 Office Manager & Music Coordinator Test Project", in the Results and Job Report you'll see there is a double-up of some candidates. I didn't notice this before, so not sure if it's happened during one of the other bug fixes, but can you take a look and see if you can determine how this happened?

Estimation: 2 - 3 hours

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/20/17 - 11/20/17
Work session total: 3:34:40

Grand total: 3:34:40

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/21/17 - 11/21/17
Work session total: 0:08:52

Grand total: 3:43:32
