### ISSUE TITLE
Improvement in db

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#28]
with the larger "MUS002 Office & Membership Coordinator - V2" project we're still getting some small delays when it's loading the data on the page. This isn't a big deal right now but we're wondering how the app will scale with more projects and heaps more candidates over time. Is this something that can be improved?

**Comment by oskvortsov-bmt** [comment]
3 hours

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 11/21/17 - 11/21/17
Work session total: 0:25:44

Grand total: 0:25:44
