### ISSUE TITLE
Response Records

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#3]
Use Hirefy document. TASK 1. Without CSV import API(another task).
- add all needed models and relations
- implement business logic for scoring

**Comment by oskvortsov-bmt** [comment]
2-4hours

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/22/17 - 10/22/17
Work session total: 6:15:42

Grand total: 6:15:42
