### ISSUE TITLE
Survey Score Rule

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#4]
Use Hirefy document. TASK 2
- add all needed models and relations
- implement business logic for score rules

**Comment by oskvortsov-bmt** [comment]
2-4 hours

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/24/17 - 10/24/17
Work session total: 1:41:13

Grand total: 1:41:13
