### ISSUE TITLE
Printout of the response records

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#5]
Use Hirefy document. TASK 3
- add API to show all response records

**Comment by oskvortsov-bmt** [comment]
1-2 hours

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/24/17 - 10/25/17
Work session total: 1:51:31

Grand total: 1:51:31

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/25/17 - 10/25/17
Work session total: 3:04:40

Grand total: 4:56:11
