### ISSUE TITLE
Jobs API

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#7]
- add model and API for jobs
- a customer can have many jobs
- API should be ready to return Jobs reports

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/22/17 - 10/22/17
Work session total: 0:00:01

Grand total: 0:00:01

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/25/17 - 10/25/17
Work session total: 2:03:00

Grand total: 2:03:01

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/26/17 - 10/26/17
Work session total: 2:57:45

Grand total: 5:00:46
