### ISSUE TITLE
CSV importing

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#8]
- add import and safe parse CSV files
- implement it in suitable places

**Comment by oskvortsov-bmt** [comment]
2-5 hours

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/26/17 - 10/26/17
Work session total: 3:46:24

Grand total: 3:46:24
