### ISSUE TITLE
DB architecture

### ISSUE THREAD

**Issue by zaikin-andrew** [BestMood-Tech/Hirefy-api#9]
- develop an architecture for the project according to existing information

Est: 2-4hrs

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/17/17 - 10/17/17
Work session total: 1:58:41

Grand total: 1:58:41

**Comment by oskvortsov-bmt** [comment]
via Hubstaff
User: Oleg Skvortsov

Project: Hirefy-API - https://app.hubstaff.com/projects/300614
Date Range: 10/18/17 - 10/18/17
Work session total: 0:25:09

Grand total: 2:23:50
